[package]
name = "argent"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rocket = {version = "0.5.0-rc.2", features = ["json", "uuid"]}
uuid = { version = "<1.0.0", features = ["v4", "serde"]}
jwks-client = {version = "0.2.0", git = "https://github.com/doooks/jwks-client.git", rev="92407e19981ae783b8c49281ba532822c1601866" }
jsonwebtoken = {version = "8", default-features = false }

[dependencies.sqlx]
version = "0.5"
default-features = false
features = ["macros", "offline", "migrate", "uuid", "time"]

[dependencies.rocket_db_pools]
version = "0.1.0-rc.2"
features = ["sqlx_postgres"]
